# Generated by Django 2.0.6 on 2018-06-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('DOJ', models.DateTimeField()),
                ('DOL', models.DateTimeField(blank=True)),
            ],
        ),
    ]
