# Generated by Django 2.0.6 on 2018-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DOL',
            field=models.DateTimeField(),
        ),
    ]
