# Generated by Django 2.0.6 on 2018-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20180619_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default=1, upload_to='Profile'),
            preserve_default=False,
        ),
    ]
