# Generated by Django 2.0.6 on 2018-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image1',
            field=models.ImageField(default=1, upload_to='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='image2',
            field=models.ImageField(default=0, upload_to='Profile'),
            preserve_default=False,
        ),
    ]
