# Generated by Django 2.0.6 on 2018-06-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20180619_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image2',
        ),
        migrations.AddField(
            model_name='member',
            name='Mobile_no',
            field=models.IntegerField(default=90, max_length=10),
            preserve_default=False,
        ),
    ]
