# Generated by Django 2.0.6 on 2018-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20180620_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Mobile_no',
            field=models.IntegerField(),
        ),
    ]
