# Generated by Django 2.0.6 on 2018-06-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_manager_manager_cpass'),
        ('main_page', '0010_member_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_expense',
            old_name='date',
            new_name='date_exp',
        ),
        migrations.AddField(
            model_name='member_expense',
            name='manager_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager'),
            preserve_default=False,
        ),
    ]
